In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv('data/imdb-top-1000.csv')
movies.head(1)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0

In [7]:
# Creates groups by categorial data (Genre)

genres = movies.groupby('Genre')
genres

In [ ]:
# Apply built-in aggregation functions

genres.mean(numeric_only=True)
# set numeric_only = True explicitly to calculate mean on numeric values only

              Runtime  IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419  420246.581395  1.897224e+08  73.419580
Adventure  134.111111     7.937500  313557.819444  1.319017e+08  78.437500
Animation   99.585366     7.930488  268032.073171  1.784326e+08  81.093333
Biography  136.022727     7.938636  272805.045455  9.404952e+07  76.240506
Comedy     112.129032     7.901290  178195.658065  1.010572e+08  78.720000
Crime      126.392523     8.016822  313398.271028  7.899656e+07  77.080460
Drama      124.737024     7.957439  212343.612457  1.225259e+08  79.701245
Family     107.500000     7.800000  275610.500000  2.195553e+08  79.000000
Fantasy     85.000000     8.000000   73111.000000  3.913633e+08        NaN
Film-Noir  104.000000     7.966667  122405.000000  4.197018e+07  95.666667
Horror     102.090909     7.909091  340232.363636  9.405902e+07  80.000000
Mystery    119.083333     7.975000  350250.333333  1.047014e+08  79.125000
Thriller   108.000000     7.800000   27733.000000  1.755074e+07  81.000000
Western    148.250000     8.350000  322416.250000  1.455538e+07  78.250000

In [13]:
# find the genre with highest avg IMDB rating

movies.groupby("Genre")['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [14]:
# find director with most popularity (based on number of votes)

movies.groupby("Director")['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [15]:
# find the highest rated movie of each genre (on the basis of imdb rating)

movies.groupby("Genre").sort_values('IMDB_rating').head(1)

AttributeError: 'DataFrameGroupBy' object has no attribute 'sort_values'

In [18]:
# find number of movies done by each actor 

# movies['Star1'].value_counts()

movies.groupby('Star1')['Series_Title'].count().sort_values(ascending=False)

Star1
Tom Hanks               12
Robert De Niro          11
Clint Eastwood          10
Al Pacino               10
Humphrey Bogart          9
                        ..
Zbigniew Zamachowski     1
Zooey Deschanel          1
Çetin Tekindor           1
Éric Toledano            1
Aaron Taylor-Johnson     1
Name: Series_Title, Length: 660, dtype: int64